# -*- coding: utf-8 -*-
"""Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onjiOI_BJsYrxA7kACa8CRCRVcoJ9LaD
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import fftconvolve
from skimage.restoration import richardson_lucy
import tifffile

# =========================================================
# 1. OBJETOS
# =========================================================

def generar_punto(size=25, intensidad=1.0):
    obj = np.zeros((size, size))
    obj[size//2, size//2] = intensidad
    return obj


def generar_dos_puntos(size=25, d=2, intensidad=1.0):
    obj = np.zeros((size, size))
    c = size // 2
    obj[c, c - d] = intensidad
    obj[c, c + d] = intensidad
    return obj


# =========================================================
# 2. PSF
# =========================================================

def psf_gaussiana(size=25, sigma=2):
    ax = np.arange(-size//2, size//2)
    xx, yy = np.meshgrid(ax, ax)
    psf = np.exp(-(xx**2 + yy**2) / (2. * sigma**2))
    return psf / psf.sum()


# =========================================================
# 3. FORWARD
# =========================================================

def formar_imagen(obj, psf):
    return fftconvolve(obj, psf, mode='same')


# =========================================================
# 4. RUIDO (Poisson)
# =========================================================

def agregar_ruido(imagen, N_fotones=1000):
    imagen = np.clip(imagen, 0, None)
    return np.random.poisson(imagen * N_fotones) / N_fotones


# =========================================================
# 5. RL
# =========================================================

def deconv_rl(imagen, psf, iteraciones=20):
    return richardson_lucy(imagen, psf, num_iter=iteraciones)


# =========================================================
# 6. GUARDAR TIFF
# =========================================================

def guardar_tif(nombre, imagen):
    img = np.clip(imagen, 0, 1)
    img = (img * 65535).astype(np.uint16)
    tifffile.imwrite(nombre, img)


# =========================================================
# 7. PIPELINE
# =========================================================

def pipeline(obj, psf, guardar=True):

    blur = formar_imagen(obj, psf)
    blur = np.clip(blur, 0, None)

    noisy = agregar_ruido(blur)

    rl_10 = deconv_rl(noisy, psf, iteraciones=10)
    rl_50 = deconv_rl(noisy, psf, iteraciones=500)

    # --- GUARDAR ---
    if guardar:
        guardar_tif("obj.tif", obj)
        guardar_tif("psf.tif", psf)
        guardar_tif("blur.tif", blur)
        guardar_tif("noisy.tif", noisy)
        guardar_tif("rl_10.tif", rl_10)
        guardar_tif("rl_50.tif", rl_50)

    # =====================================================
    # PLOTS CON EJES Y ESCALA
    # =====================================================

    fig, axs = plt.subplots(2, 3, figsize=(12, 8))

    imagenes = [obj, psf, blur, noisy, rl_10, rl_50]
    titulos = ["Objeto", "PSF", "Blur", "Noisy", "RL (10 iter)", "RL (50 iter)"]

    pixel_size = 1.0  # cambiar a micrones si querés

    for ax, img, title in zip(axs.ravel(), imagenes, titulos):

        im = ax.imshow(
            img,
            cmap='gray',
            extent=[0, img.shape[1]*pixel_size, 0, img.shape[0]*pixel_size],
            origin='lower'
        )

        ax.set_title(title)
        ax.set_xlabel("X (pixels)")
        ax.set_ylabel("Y (pixels)")

        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    plt.tight_layout()
    plt.show()

    return obj, blur, noisy, rl_10, rl_50


# =========================================================
# 8. RUN
# =========================================================

# Elegir objeto
obj = generar_dos_puntos(d=2)   # probá con d=1,2,3,4
# obj = generar_punto()

psf = psf_gaussiana(size=25, sigma=2)

obj, blur, noisy, rl_10, rl_50 = pipeline(obj, psf, guardar=True)


# =========================================================
# 9. DESCARGA (COLAB)
# =========================================================

import zipfile
from google.colab import files

with zipfile.ZipFile("resultados.zip", "w") as z:
    z.write("obj.tif")
    z.write("psf.tif")
    z.write("blur.tif")
    z.write("noisy.tif")
    z.write("rl_10.tif")
    z.write("rl_50.tif")

#files.download("resultados.zip")

def generar_puntos_aleatorios(size=256, n_puntos=10, intensidad=1.0, distancia_min=0):
    obj = np.zeros((size, size))

    coords = []

    intentos_max = 10000  # para evitar loops infinitos
    intentos = 0

    while len(coords) < n_puntos and intentos < intentos_max:
        x = np.random.randint(0, size)
        y = np.random.randint(0, size)

        # chequeo de distancia mínima
        if distancia_min > 0:
            valido = True
            for (cx, cy) in coords:
                if np.sqrt((x - cx)**2 + (y - cy)**2) < distancia_min:
                    valido = False
                    break
            if not valido:
                intentos += 1
                continue

        coords.append((x, y))
        obj[y, x] = intensidad
        intentos += 1

    if len(coords) < n_puntos:
        print("⚠️ No se pudieron ubicar todos los puntos con la distancia mínima dada")

    return obj

obj = generar_puntos_aleatorios(
    size=25,
    n_puntos=20,
    distancia_min=1
)

pipeline(obj, psf)

